import 'package:hive/hive.dart';
import 'package:selavu/walletprovider.dart';

part 'expense.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0) // Unique ID for this type
class Expense {
  @HiveField(0)
  final double amount;

  @HiveField(1)
  final String category;

  @HiveField(2)
  final String description;

  @HiveField(3)
  final DateTime date;

  @HiveField(4) // New field to store the username
  final String username;

  Expense({
    required this.amount,
    required this.category,
    required this.description,
    required this.date,
    required this.username,
    // Ensure the username is passed to the constructor
  });
}
